config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/signup' => 'devise/registrations#new'
    get '/profile/update' => 'devise/registrations#edit'
    get '/profile/password' => 'devise/passwords#edit'
  end
  root 'home#index'
  resources :users, :controler => "user"
  resources :admins, :controler => "admin"
  post '/users/ativar/:id' => 'users#ativar', as: 'ativar'
  post '/users/desativar/:id' => 'users#desativar', as: 'desativar'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  validates_length_of :celular, within: 8..9, message: "Digite um numero de celular.", unless: :isAdmin
  validates_length_of :telefone, within: 8..9, message: "Digite um numero de telefone.", unless: :isAdmin

  private

  def isAdmin
    self.admin
  end  
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :verify_user

  def index
    @admins = User.where(admin: true).paginate(:page => params[:page])
  end

  def new
    @admin = User.new
  end

  def create  
    @admin = User.new(user_params)
    @admin.admin = true
    if @admin.save
      flash[:notice] = "Admin criado."
      redirect_to admins_path
    else
      render :new
    end
  end

  def edit
    @admin = User.find(params[:id]) 
  end

  def update
    @admin = User.find(params[:id])
    if @admin.update(user_params)
      flash[:notice] = "Usuario criado"
      redirect_to admins_path
    else
      render :edit
    end
  end

  def destroy
    @admin = User.find(params[:id])
    @admin.destroy
    redirect_to admins_path
  end

  protected

  def verify_user
    unless current_user.admin
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :password, :confirm_password, :fullname, :celular, :telefone, :avatar, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password, :confirm_password, :current_password, :fullname, :celular, :telefone, :avatar, :avatar, :avatar_cache, :remove_avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    latitude = request.location.latitude
    longitude = request.location.longitude
    @users = User.where([:admin => false, :status => 'ativo']).near([latitude, longitude], 100000, :units => :km).paginate(page: params[:page], per_page: 20)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if current_user.admin
      respond_to do |format|
      format.html
      format.json{render json: UsersDatatable.new(view_context)}
    end
    else
      redirect_to root_path
    end
  end

  def show
      @user = User.find(params[:id])
  end

  def ativar
    if current_user.admin
      User.update((params[:id]), :status => 'ativo')
    else
      redirect_to root_path  
    end  
  end
  helper_method :ativar

  def desativar
    if current_user.admin
      User.update((params[:id]), :status => 'inativo')
    else
      redirect_to root_path
    end
  end

  helper_method :desativar

  def update
    if current_user.admin
      @user = User.find(params[:id])
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if @user.udapte(user_params)
        flash[:notice] = "Status alterado."
      else
        flash[:notice] = "Erro."
      end  
    else
      redirect_to root_path
    end
    
  end
  
  private

  def user_params
    params.require(:user).permit(:status)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for @admin, :url {:action => "create_admins"}, :html{:method => 'post'}} do |f|  %>
    <%= f.input :email, required: true %>
    <%= f.input :password, required: true %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.button :submit, "Salvar" %>
<% end %>

app/views/admins/edit.html.erb
<%= simple_form_for @admin do |f|  %>
    <%= f.input :email, required: true %>
    <%= f.input :password, required: true %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.button :submit, "Salvar" %>
<% end %>

app/views/admins/index.html.erb
<h1>Admins</h1>

<table class="table table-striped table-condensed">
    <tbody>
        <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.email %></td>
            <td><%= link_to "Deletar", admin_path(admin),data: { confirm: "Confirma exclusão?"}, :method => :delete, class: 'btn btn-danger btn-small' %></td>
          </tr>
        <% end %>
    </tbody>
</table>
<%= will_paginate @admin %>

<%= link_to '+ Admin', new_admin_path, class: 'btn btn-primary btn-sm' %>

app/views/admins/new.html.erb
<%= form_for @admin, :url => {:action => 'create'} do |f|  %>
    <%= f.text_field :email, required: true %>
    <%= f.password_field :password, required: true %>
    <%= f.password_field :password_confirmation, required: true %>
    <%= f.submit "Salvar" %>
<% end %>

app/views/admins/show.html.erb
<h1>Usuário</h1>
<% @admins.each do |@admin| %>
  <p><%= admin.email %></p>
<% end %>

app/views/home/index.html.erb
<h1>Home</h1>

<table class="table table-condensed table-striped">
    <thead>
        <th>Avatar</th>
        <th>Nome de Usuário</th>
        <th>Nome Completo</th>
        <th>Email</th>
        <th>Celular</th>
        <th>Telefone</th>
        <th>Distância</th>
    </thead>
    <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.avatar.thumbnail %></td>
            <td><%= user.username %></td>
            <td><%= user.fullname%></td>
            <td><%= user.email %></td>
            <td><%= user.celular %></td>
            <td><%= user.telefone %></td>
            <td><%= user.distance.round(2) %> Kms</td>
          </tr>
        <% end %>
    </tbody>
</table>
  
<%= will_paginate @users %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arcond</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'Arcond', root_path, class: 'navbar-brand' %>
      </div>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Profissionais', root_path %></li>
          <% if current_user %>
            <% if current_user.admin %>
              <li><%= link_to 'Usuários', users_path %></li>
              <li><%= link_to 'Admins', admins_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to 'Cadastre-se', signup_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to current_user.email, profile_update_path %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Listar Usuários</h1>

<table class="table table-condensed table-striped" id="users", data-source="<%= users_path(format: :json) %>">
    <thead>
        <th>Nome de Usuário</th>
        <th>Nome Completo</th>
        <th>Email</th>
        <th>Celular</th>
        <th>Telefone</th>
        <th>Status</th>
        <th>Edit</th>
    </thead>
    <tbody>
    </tbody>
</table>
  

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
    <h1 class="com-sm-12">Nome de Usuário: <%= @user.username %></h1>
    <%= image_tag @user.avatar.small, class: "col-sm-6" %>
    <div class="col-sm-6">
        <p>Nome: <%= @user.fullname %></p>
        <p>Email: <%= @user.email %></p>
        <p>Telefone: <%= @user.telefone %></p>
        <p>Celular: <%= @user.celular %></p>
        <p>Endereco: <%= @user.address %></p>
        <p>
            Status: <%= @user.status %> |
            <% if @user.status != 'ativo' %>
              <%= link_to('Ativar', ativar_path(@user), :method => :post, class: 'btn btn-success btn-sm', remote: true) %>
            <% else %>
              <%= link_to('Desativar', desativar_path(@user), :method => :post, :id => 'desativar', class: 'btn btn-danger btn-sm', remote: true) %>
            <% end %>
        </p>
    </div>
</div>